'use client';
import React, { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { useOffers } from '@/hooks/useP2P';
import { OfferCard } from '@/components/p2p/OfferCard';
import { CreateOfferModal } from '@/components/p2p/CreateOfferModal';
import { Button, Select, Input, Spinner, Alert } from '@/components/ui';
import { CURRENCIES, PAYMENT_METHODS } from '@/lib/format';
import { OfferType } from '@/types/p2p';

export default function P2PMarketplace() {
  const [offerType, setOfferType]     = useState<OfferType>('SELL');
    const [currency, setCurrency]       = useState('');
      const [payMethod, setPayMethod]     = useState('');
        const [amount, setAmount]           = useState('');
          const [showCreate, setShowCreate]   = useState(false);
            const [currentUserId, setUserId]    = useState<string | undefined>();

              // Current user
                useEffect(() => {
                    supabase.auth.getUser().then(({ data }) => setUserId(data.user?.id));
                      }, []);

                        const filters = {
                            type:          offerType,
                                currency,
                                    paymentMethod: payMethod,
                                        amount:        amount ? parseFloat(amount) : null,
                                          };

                                            const { offers, loading, error, refetch } = useOffers(filters);

                                              return (
                                                  <main className="min-h-screen bg-[#0d0d1a] text-white p-4 md:p-8">
                                                        {/* ── Header ── */}
                                                              <div className="max-w-5xl mx-auto">
                                                                      <div className="flex items-center justify-between mb-8">
                                                                                <div>
                                                                                            <h1 className="text-3xl font-extrabold text-white">
                                                                                                          <span className="text-yellow-400">Hanakalo</span> P2P
                                                                                                                      </h1>
                                                                                                                                  <p className="text-gray-400 text-sm mt-1">Échangez directement entre utilisateurs TakaloCash</p>
                                                                                                                                            </div>
                                                                                                                                                      <Button variant="primary" onClick={() => setShowCreate(true)}>
                                                                                                                                                                  + Créer une offre
                                                                                                                                                                            </Button>
                                                                                                                                                                                    </div>

                                                                                                                                                                                            {/* ── Type Toggle ── */}
                                                                                                                                                                                                    <div className="flex rounded-2xl overflow-hidden border border-white/10 mb-6">
                                                                                                                                                                                                              {(['SELL', 'BUY'] as OfferType[]).map(t => (
                                                                                                                                                                                                                          <button key={t} onClick={() => setOfferType(t)}
                                                                                                                                                                                                                                        className={`flex-1 py-3.5 text-sm font-bold transition-colors ${offerType === t
                                                                                                                                                                                                                                                        ? t === 'SELL'
                                                                                                                                                                                                                                                                          ? 'bg-green-500/20 text-green-400 border-b-2 border-green-400'
                                                                                                                                                                                                                                                                                            : 'bg-blue-500/20 text-blue-400 border-b-2 border-blue-400'
                                                                                                                                                                                                                                                                                                            : 'bg-white/5 text-gray-400 hover:bg-white/8'}`}>
                                                                                                                                                                                                                                                                                                                          {t === 'SELL'
                                                                                                                                                                                                                                                                                                                                          ? '📤 J\'achète des crypto (offres VENTE)'
                                                                                                                                                                                                                                                                                                                                                          : '📥 Je vends des crypto (offres ACHAT)'}
                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                {/* ── Filters ── */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                  <Select label="Devise" value={currency} onChange={e => setCurrency(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Toutes</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {CURRENCIES.map(c => <option key={c}>{c}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Select label="Paiement" value={payMethod} onChange={e => setPayMethod(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="">Tous</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {PAYMENT_METHODS.map(m => <option key={m}>{m}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Input label="Montant (crypto)" type="number" placeholder="ex: 50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={amount} onChange={e => setAmount(e.target.value)} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="ghost" onClick={() => { setCurrency(''); setPayMethod(''); setAmount(''); }} className="w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Réinitialiser
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* ── Table header ── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="hidden md:grid grid-cols-[1fr_auto_auto_auto_auto] gap-4 px-5 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>Trader</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-right">Taux</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-right">Limite crypto</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-right">Valeur MGA</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* ── Offers list ── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="py-20"><Spinner size={40} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : error ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Alert type="error">{error}</Alert>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : offers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center py-20 text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-5xl mb-4">🔍</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="font-semibold">Aucune offre disponible</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm mt-1">Modifiez vos filtres ou créez la première offre.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-col gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {offers.map(o => <OfferCard key={o.id} offer={o} currentUserId={currentUserId} />)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* ── Count ── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!loading && offers.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-center text-xs text-gray-600 mt-6">{offers.length} offre{offers.length > 1 ? 's' : ''} disponible{offers.length > 1 ? 's' : ''}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* ── Create modal ── */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <CreateOfferModal open={showCreate} onClose={() => setShowCreate(false)} onSuccess={refetch} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }