'use client';
import { useState, useEffect, useCallback, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { P2POffer, P2PTrade, ChatMessage, OfferFilters, TradeStatus } from '@/types/p2p';

// ─────────────────────────────────────────────
// useOffers — fetch + realtime P2P offers
// ─────────────────────────────────────────────
export function useOffers(filters: OfferFilters) {
  const [offers, setOffers]   = useState<P2POffer[]>([]);
    const [loading, setLoading] = useState(true);
      const [error, setError]     = useState<string | null>(null);

        const fetchOffers = useCallback(async () => {
            setLoading(true);
                setError(null);
                    try {
                          let q = supabase
                                  .from('p2p_offers')
                                          .select(`*, profile:profiles(*)`)
                                                  .eq('status', 'ACTIVE')
                                                          .eq('type', filters.type)
                                                                  .order('created_at', { ascending: false });

                                                                        if (filters.currency)
                                                                                q = q.eq('from_currency', filters.currency);
                                                                                      if (filters.paymentMethod)
                                                                                              q = q.contains('payment_methods', [filters.paymentMethod]);
                                                                                                    if (filters.amount != null) {
                                                                                                            q = q.lte('min_amount', filters.amount).gte('max_amount', filters.amount);
                                                                                                                  }

                                                                                                                        const { data, error: err } = await q;
                                                                                                                              if (err) throw err;
                                                                                                                                    setOffers(data as P2POffer[]);
                                                                                                                                        } catch (e: any) {
                                                                                                                                              setError(e.message);
                                                                                                                                                  } finally {
                                                                                                                                                        setLoading(false);
                                                                                                                                                            }
                                                                                                                                                              }, [filters]);

                                                                                                                                                                useEffect(() => { fetchOffers(); }, [fetchOffers]);

                                                                                                                                                                  // Realtime subscription on p2p_offers
                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                        const channel = supabase
                                                                                                                                                                              .channel('p2p_offers_realtime')
                                                                                                                                                                                    .on('postgres_changes', { event: '*', schema: 'public', table: 'p2p_offers' },
                                                                                                                                                                                            () => fetchOffers())
                                                                                                                                                                                                  .subscribe();
                                                                                                                                                                                                      return () => { supabase.removeChannel(channel); };
                                                                                                                                                                                                        }, [fetchOffers]);

                                                                                                                                                                                                          return { offers, loading, error, refetch: fetchOffers };
                                                                                                                                                                                                          }

                                                                                                                                                                                                          // ─────────────────────────────────────────────
                                                                                                                                                                                                          // useTrade — single trade with realtime
                                                                                                                                                                                                          // ─────────────────────────────────────────────
                                                                                                                                                                                                          export function useTrade(tradeId: string) {
                                                                                                                                                                                                            const [trade, setTrade]     = useState<P2PTrade | null>(null);
                                                                                                                                                                                                              const [loading, setLoading] = useState(true);
                                                                                                                                                                                                                const [error, setError]     = useState<string | null>(null);

                                                                                                                                                                                                                  const fetchTrade = useCallback(async () => {
                                                                                                                                                                                                                      const { data, error: err } = await supabase
                                                                                                                                                                                                                            .from('p2p_trades')
                                                                                                                                                                                                                                  .select(`
                                                                                                                                                                                                                                          *,
                                                                                                                                                                                                                                                  offer:p2p_offers(*),
                                                                                                                                                                                                                                                          buyer_profile:profiles!buyer_id(*),
                                                                                                                                                                                                                                                                  seller_profile:profiles!seller_id(*)
                                                                                                                                                                                                                                                                        `)
                                                                                                                                                                                                                                                                              .eq('id', tradeId)
                                                                                                                                                                                                                                                                                    .single();
                                                                                                                                                                                                                                                                                        if (err) setError(err.message);
                                                                                                                                                                                                                                                                                            else setTrade(data as P2PTrade);
                                                                                                                                                                                                                                                                                                setLoading(false);
                                                                                                                                                                                                                                                                                                  }, [tradeId]);

                                                                                                                                                                                                                                                                                                    useEffect(() => { fetchTrade(); }, [fetchTrade]);

                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                          const channel = supabase
                                                                                                                                                                                                                                                                                                                .channel(`trade_${tradeId}`)
                                                                                                                                                                                                                                                                                                                      .on('postgres_changes',
                                                                                                                                                                                                                                                                                                                              { event: 'UPDATE', schema: 'public', table: 'p2p_trades', filter: `id=eq.${tradeId}` },
                                                                                                                                                                                                                                                                                                                                      (payload) => setTrade(prev => prev ? { ...prev, ...(payload.new as Partial<P2PTrade>) } : prev))
                                                                                                                                                                                                                                                                                                                                            .subscribe();
                                                                                                                                                                                                                                                                                                                                                return () => { supabase.removeChannel(channel); };
                                                                                                                                                                                                                                                                                                                                                  }, [tradeId]);

                                                                                                                                                                                                                                                                                                                                                    return { trade, loading, error, refetch: fetchTrade };
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                    // useChat — realtime chat messages
                                                                                                                                                                                                                                                                                                                                                    // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                    export function useChat(tradeId: string) {
                                                                                                                                                                                                                                                                                                                                                      const [messages, setMessages]       = useState<ChatMessage[]>([]);
                                                                                                                                                                                                                                                                                                                                                        const [sending, setSending]         = useState(false);
                                                                                                                                                                                                                                                                                                                                                          const bottomRef = useRef<HTMLDivElement>(null);

                                                                                                                                                                                                                                                                                                                                                            const fetchMessages = useCallback(async () => {
                                                                                                                                                                                                                                                                                                                                                                const { data } = await supabase
                                                                                                                                                                                                                                                                                                                                                                      .from('chat_messages')
                                                                                                                                                                                                                                                                                                                                                                            .select(`*, sender:profiles!sender_id(*)`)
                                                                                                                                                                                                                                                                                                                                                                                  .eq('trade_id', tradeId)
                                                                                                                                                                                                                                                                                                                                                                                        .order('created_at', { ascending: true });
                                                                                                                                                                                                                                                                                                                                                                                            setMessages((data as ChatMessage[]) ?? []);
                                                                                                                                                                                                                                                                                                                                                                                              }, [tradeId]);

                                                                                                                                                                                                                                                                                                                                                                                                useEffect(() => { fetchMessages(); }, [fetchMessages]);

                                                                                                                                                                                                                                                                                                                                                                                                  // Scroll to bottom on new messages
                                                                                                                                                                                                                                                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                        bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
                                                                                                                                                                                                                                                                                                                                                                                                          }, [messages]);

                                                                                                                                                                                                                                                                                                                                                                                                            // Realtime subscription
                                                                                                                                                                                                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                  const channel = supabase
                                                                                                                                                                                                                                                                                                                                                                                                                        .channel(`chat_${tradeId}`)
                                                                                                                                                                                                                                                                                                                                                                                                                              .on('postgres_changes',
                                                                                                                                                                                                                                                                                                                                                                                                                                      { event: 'INSERT', schema: 'public', table: 'chat_messages', filter: `trade_id=eq.${tradeId}` },
                                                                                                                                                                                                                                                                                                                                                                                                                                              async (payload) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Fetch full message with profile join
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { data } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .from('chat_messages')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .select(`*, sender:profiles!sender_id(*)`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .eq('id', payload.new.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data) setMessages(prev => [...prev, data as ChatMessage]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .subscribe();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return () => { supabase.removeChannel(channel); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, [tradeId]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const sendMessage = async (text: string, attachmentUrl?: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!text.trim() && !attachmentUrl) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setSending(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const { data: { user } } = await supabase.auth.getUser();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await supabase.from('chat_messages').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trade_id:       tradeId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sender_id:      user?.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message:        text.trim(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          attachment_url: attachmentUrl ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                is_system:      false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setSending(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { messages, sending, sendMessage, bottomRef };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // useCountdown — counts down from expires_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export function useCountdown(expiresAt: string | null): number {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [seconds, setSeconds] = useState(0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!expiresAt) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const update = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const diff = Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setSeconds(diff);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            update();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const timer = setInterval(update, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return () => clearInterval(timer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, [expiresAt]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return seconds;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // useTradeActions — RPC calls for trade actions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export function useTradeActions(tradeId: string, refetch: () => void) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const [busy, setBusy] = useState(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [error, setError] = useState<string | null>(null);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const call = async (action: () => Promise<void>) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setBusy(true); setError(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try { await action(); refetch(); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          catch (e: any) { setError(e.message); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              finally { setBusy(false); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const markPaid = () => call(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('p2p_trades').update({ status: 'PAID' as TradeStatus }).eq('id', tradeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (error) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await supabase.from('chat_messages').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          trade_id: tradeId, sender_id: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: '💳 Buyer has marked the trade as PAID. Seller — please verify and release.', is_system: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const releaseEscrow = () => call(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { error } = await supabase.rpc('release_escrow_crypto', { p_trade_id: tradeId });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (error) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const cancelTrade = () => call(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data: trade } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .from('p2p_trades').select('status, seller_id, amount_crypto, offer_id').eq('id', tradeId).single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!trade) throw new Error('Trade not found');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (trade.status === 'PAID') throw new Error('Cannot cancel — buyer already paid.');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Return locked balance to seller if PENDING
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (trade.status === 'PENDING') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { data: offer } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('p2p_offers').select('from_currency').eq('id', trade.offer_id).single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (offer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await supabase.from('balances')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .update({ available: supabase.rpc('increment', { x: trade.amount_crypto }), locked_balance: supabase.rpc('decrement', { x: trade.amount_crypto }) })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .eq('user_id', trade.seller_id).eq('currency', offer.from_currency);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await supabase.from('p2p_trades').update({ status: 'CANCELLED' as TradeStatus }).eq('id', tradeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await supabase.from('chat_messages').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trade_id: tradeId, sender_id: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: '❌ Trade has been cancelled.', is_system: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const openDispute = (reason: string) => call(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await supabase.from('p2p_trades')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .update({ status: 'DISPUTE' as TradeStatus, dispute_reason: reason }).eq('id', tradeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await supabase.from('chat_messages').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trade_id: tradeId, sender_id: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              message: `⚠️ Dispute opened: "${reason}". Admin will review within 24h.`, is_system: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return { busy, error, markPaid, releaseEscrow, cancelTrade, openDispute };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }